services:

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile

    container_name: laravel_app

    restart: unless-stopped

    ports:
      - "8080:80"

    volumes:
      - ./:/var/www/html

    depends_on:
      - postgres

    networks:
      - laravel

  postgres:
    image: postgres:16

    container_name: postgres_db

    restart: unless-stopped

    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - laravel

volumes:
  postgres_data:

networks:
  laravel:
